# Generated by Django 3.1.4 on 2021-01-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20210123_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('src_twt', models.TextField(max_length=15728640)),
                ('label', models.IntegerField(null=True)),
                ('detect_type', models.CharField(default='unk', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit_timestamp', models.DateTimeField(auto_now=True)),
                ('new_add', models.IntegerField(default=1)),
                ('user_isExist', models.IntegerField(default=1)),
                ('true_label', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(default='user1.jpg', upload_to='media')),
                ('name', models.CharField(max_length=64)),
                ('twitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RD.twitter')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10485760)),
                ('twitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RD.twitter')),
            ],
        ),
    ]
