# Generated by Django 3.1.3 on 2021-01-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210123_2359'),
        ('RD', '0002_auto_20210126_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chinese',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.TextField(max_length=2097152)),
                ('comment', models.TextField(max_length=15728640)),
                ('label', models.IntegerField(null=True)),
                ('detect_type', models.CharField(default='unk', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit_timestamp', models.DateTimeField(auto_now=True)),
                ('new_add', models.IntegerField(default=1)),
                ('user_isExist', models.IntegerField(default=1)),
                ('true_label', models.IntegerField(null=True)),
                ('image_path', models.ImageField(default='user1.jpg', null=True, upload_to='media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
            options={
                'verbose_name': '中文评论',
                'verbose_name_plural': '中文评论',
                'ordering': ['-create_time'],
            },
        ),
    ]
