# Generated by Django 3.1.3 on 2021-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RD', '0004_auto_20210126_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinese',
            name='comment',
            field=models.TextField(max_length=15728640),
        ),
        migrations.AlterField(
            model_name='chinese',
            name='source',
            field=models.TextField(max_length=1048576),
        ),
    ]
