# Generated by Django 3.1.4 on 2021-01-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-user_c_time'], 'verbose_name': '普通用户', 'verbose_name_plural': '普通用户'},
        ),
    ]
