# Generated by Django 3.1.3 on 2021-01-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='用户账号')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('user_nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('user_password', models.CharField(max_length=128, verbose_name='密码')),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('user_phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('user_table', models.CharField(max_length=11, verbose_name='谣言表')),
                ('user_c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-user_c_time'],
            },
        ),
    ]
