# Generated by Django 3.1.3 on 2021-01-26 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='img',
            options={'verbose_name': '传播路径图', 'verbose_name_plural': '传播路径图'},
        ),
        migrations.AlterModelOptions(
            name='twitter',
            options={'ordering': ['-create_time'], 'verbose_name': '原贴', 'verbose_name_plural': '原贴'},
        ),
    ]
