# Generated by Django 3.1.3 on 2021-01-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RD', '0003_chinese'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chinese',
            options={'ordering': ['-create_time'], 'verbose_name': '中文帖子', 'verbose_name_plural': '中文帖子'},
        ),
        migrations.AlterField(
            model_name='chinese',
            name='comment',
            field=models.TextField(max_length=52428800),
        ),
        migrations.AlterField(
            model_name='chinese',
            name='source',
            field=models.TextField(max_length=15728640),
        ),
    ]
