# Generated by Django 3.1.3 on 2021-01-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RD', '0005_auto_20210126_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinese',
            name='source_seq',
            field=models.TextField(default='sentence', max_length=51200),
        ),
        migrations.AlterField(
            model_name='chinese',
            name='comment',
            field=models.TextField(max_length=6291456),
        ),
        migrations.AlterField(
            model_name='chinese',
            name='source',
            field=models.TextField(max_length=524288),
        ),
    ]
